name: Deploy to Azure Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  ENV: ${{ secrets.ENV }}
  IMAGE_NAME: chat-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: $

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: $AZURE_CONTAINER_REGISTRY
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd src/
          docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest .
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest
